@startuml domain-model
 
!include settings.puml

enum EstadoCita {
    PENDIENTE
    CONFIRMADA
    REPROGRAMADA
    SIN_ASISTENCIA_CLIENTE
    SIN_ASISTENCIA_PROVEEDOR
    EN_ATENCION
    CANCELADA
    COMPLETADA
}


enum EstadoTratamiento {
    EN_PROGRESO
    NO_COMPLETADO
    COMPLETADO
}

enum TipoExamen {
    RADIOGRAFIA
    OTRO
}

enum EstadoExamen {
    PENDIENTE
    REVISADO
}

enum EstadoPiezaDental {
    SANO
    CARIES
    REPARADO
    CORONA
    EXTRAIDO
}

'enum TipoCliente {
'		NIÑO
'		ADULTO
'		ANCIANO
'}

enum Complejidad {
    SIMPLE
    MODERADA
    COMPLEJA
}

enum TipoNotificacion {
		EMAIL
		SMS
		PUSH
}

class Sesion {
    +numeroSesion: int
    +notas: String
}

class Tratamiento {
    +fechaInicio: Date
    +sesionesEstimadas: int
    +observaciones: String
}

class Servicio {
    +descripcion: String
    +duracionEstimada: int
    +costo: decimal
}

enum MotivoConsulta {
'    # Urgencias
    DOLOR_AGUDO
    FRACTURA_DENTAL
    TRAUMA_DENTAL
    SANGRADO_ENCIAS
    HINCHAZON_ABSCESO
    PERDIDA_RESTAURACION
    SENSIBILIDAD_SEVERA
'    # Preventivas
    CHEQUEO_GENERAL
    LIMPIEZA_PERIODICA
    REVISION_RUTINA
    CONTROL_POST_TRATAMIENTO
'    Específicas
    DOLOR_AL_MASTICAR
    MAL_ALIENTO
    MOVILIDAD_DENTAL
    CAMBIO_COLOR
    PROBLEMA_PROTESIS
    PROBLEMA_MORDIDA
'    Estéticas
    BLANQUEAMIENTO
    CORRECCION_SONRISA
    CARILLAS
    OTRO
}


enum TipoServicio {
    PREVENCION
    ODONTOLOGIA_GENERAL
    ENDODONCIA
    CIRUGIA
    ORTODONCIA
    ESTETICA
    OTRO
}

class Cita {
	+ descripcion: String
}

compositionRelation(SistemaOdontologico, Cliente, ONE_TO_MANY)
compositionRelation(SistemaOdontologico, Proveedor, ONE_TO_MANY)
compositionRelation(SistemaOdontologico, SistemaReservaCita, ONE_TO_ONE)

'compositionRelation(Cliente, TipoCliente, ONE_TO_ONE)

aggregationRelation(SistemaReservaCita, Cita, ZERO_TO_MANY, DOWN)
compositionRelation(SistemaReservaCita, Calendario, ONE_TO_ONE)
compositionRelation(Cita, EstadoCita, ONE_TO_ONE, LEFT)
compositionRelation(Cita, MotivoConsulta, ONE_TO_MANY)
aggregationRelation(Cita, Cliente, ONE_TO_ONE)
aggregationRelation(Cita, Proveedor, ONE_TO_ONE)
'associationRelation(Cita, AtencionOdontologica, ONE_TO_ONE,)

aggregationRelation(SistemaOdontologico, HistorialClinico, ONE_TO_MANY, RIGHT)
aggregationRelation(HistorialClinico, Cliente, ONE_TO_ONE)
aggregationRelation(HistorialClinico, AtencionOdontologica, ONE_TO_MANY)

compositionRelation(AtencionOdontologica, Diagnostico, ONE_TO_ONE)
aggregationRelation(AtencionOdontologica, Proveedor, ONE_TO_ONE, UP)
aggregationRelation(AtencionOdontologica, Cliente, ONE_TO_ONE, UP)

compositionRelation(Diagnostico, Tratamiento, ONE_TO_ONE)
compositionRelation(Tratamiento, EstadoTratamiento, ONE_TO_ONE)
compositionRelation(Tratamiento, Complejidad, ONE_TO_ONE)
compositionRelation(Tratamiento, MotivoConsulta, ONE_TO_MANY, UP)

aggregationRelation(Sesion, Examen, ZERO_TO_MANY)
compositionRelation(Examen, TipoExamen, ONE_TO_ONE, RIGHT)
compositionRelation(Examen, EstadoExamen, ONE_TO_ONE, LEFT)

aggregationRelation(Tratamiento, Sesion, ONE_TO_MANY)
aggregationRelation(Sesion, Cita, ONE_TO_MANY)
compositionRelation(Sesion, Servicio, ONE_TO_MANY, DOWN)

aggregationRelation(Sesion, Odontograma, ONE_TO_ONE, DOWN)
aggregationRelation(Odontograma, PiezaDental, ONE_TO_MANY, DOWN)
compositionRelation(PiezaDental, EstadoPiezaDental, ONE_TO_ONE, RIGHT)

compositionRelation(Servicio, TipoServicio, ONE_TO_ONE, RIGHT)
aggregationRelation(Tratamiento, Servicio, ONE_TO_MANY)

useRelation(Calendario, Cita, ONE_TO_MANY)
useRelation(Calendario, Recordatorio, ONE_TO_MANY)
useRelation(Calendario, Notificacion, ONE_TO_MANY)
compositionRelation(Notificacion, TipoNotificacion, ONE_TO_MANY, LEFT)
useRelation(Recordatorio, Notificacion, ONE_TO_MANY)

@enduml 