@startuml vendor-use-cases-context
!include settings.puml

state(INITIAL_STATE, AUTENTICACION)
state(AUTENTICACION, ABIERTO_APP)

state ABIERTO_VISITAS_CITAS: Mostrar detalles de citas\nCrear actividad técnica\nMostrar citas realizadas
state ABIERTO_ACTIVIDADES_CALENDARIO: Mostrar eventos\nFiltrar eventos
state ABIERTO_ACTIVIDADES_SERVICIOS: CRUD de actividades
state ABIERTO_ACTIVIDADES_TRATAMIENTOS: CRUD de actividades

state ABIERTO_CALENDARIO: Mostrar detalles de calendario
state(ABIERTO_APP, ABIERTO_VISITAS_CITAS, LEFT)
state(ABIERTO_APP,ABIERTO_ACTIVIDADES_CALENDARIO, RIGHT)
@enduml